name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./cuddly_chainsaw
      with:
        pr-message: 'Message that will be displayed on users'' first pr'
