name: Greetings

on: [pull_request, issues, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm run build
    - uses: ./
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
